function thetaddot = Thetaddot(theta,thetadot,u,xdot)
%Thetaddot
%    THETADDOT = Thetaddot(THETA,THETADOT,U,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Sep-2024 11:45:50

t2 = cos(theta);
t3 = sin(theta);
thetaddot = (t3.*3.43e+2+t2.*u.*5.0e+1-t2.*xdot.*5.0+t2.*t3.*thetadot.^2.*3.0)./(t2.^2.*3.0-1.4e+1);
end
